# Generated by Django 5.0.6 on 2024-10-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(unique=True),
        ),
    ]
