# Generated by Django 5.0.6 on 2024-10-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0005_remove_leaveapl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapl',
            name='status',
            field=models.CharField(choices=[('SUB', 'Submitted'), ('ACP', 'Accepted'), ('REJ', 'Rejected'), ('DEF', 'Deffered')], default='SUB', max_length=3),
        ),
    ]
